%YAML:1.0

# Project
project_name: "lvi_sam"

#common parameters公用参数
imu_topic: "/imu_raw"
image_topic: "/camera/image_raw"
point_cloud_topic: "lvi_sam/lidar/deskew/cloud_deskewed"
#激光点云
# Lidar Params雷达参数
use_lidar: 1                     # whether use depth info from lidar or not是否使用激光雷达的深度信息
lidar_skip: 3                    # skip this amount of scans跳跃的间距
align_camera_lidar_estimation: 1 # align camera and lidar estimation for visualization对准摄像机和激光雷达估算可视化

# lidar to camera extrinsic雷达到相机的矩阵
lidar_to_cam_tx: 0.05
lidar_to_cam_ty: -0.07
lidar_to_cam_tz: -0.07
lidar_to_cam_rx: 0.0
lidar_to_cam_ry: 0.0
lidar_to_cam_rz: -0.04

# camera model相机模型,鱼眼相机
model_type: MEI
camera_name: camera

# Mono camera config单目相机配置.mirror_parameters镜像参数。distortion失真参数。projection投影参数
image_width: 720
image_height: 540
mirror_parameters:
   xi: 1.9926618269451453
distortion_parameters:
   k1: -0.0399258932468764
   k2: 0.15160828121223818
   p1: 0.00017756967825777937
   p2: -0.0011531239076798612
projection_parameters:
   gamma1: 669.8940458885896
   gamma2: 669.1450614220616
   u0: 377.9459252967363
   v0: 279.63655686698144
fisheye_mask: "/config/fisheye_mask_720x540.jpg"

#imu parameters       The more accurate parameters you provide, the worse performance
acc_n: 0.02         # accelerometer measurement noise standard deviation.加速度计测量噪声标准偏差
gyr_n: 0.01         # gyroscope measurement noise standard deviation.陀螺仪测量噪声标准偏差。
acc_w: 0.002        # accelerometer bias random work noise standard deviation.加速度计偏差随机工作噪声标准偏差
gyr_w: 4.0e-5       # gyroscope bias random work noise standard deviation.陀螺仪偏置随机工作噪声标准偏差。
g_norm: 9.805       #

# Extrinsic parameter between IMU and Camera.IMU 与摄像机之间的外参数。
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.有一个准确的外部参数。我们相信下面的 imu ^ r _ cam，imu ^ t _ cam，不要改变它。
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.对外部参数有一个初始的猜测。我们将围绕你的初始猜测进行优化
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 对外部参数一无所知。你不需要放弃 r，t。我们会试着校准它。开始时做一些旋转运动。
#Rotation from camera frame to imu frame, imu^R_cam从相机帧到 imu 帧的旋转，imu ^ r _ cam。三乘三，double类型
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0, 0, -1, 
           -1, 0, 0, 
           0, 1, 0]

#Translation from camera frame to imu frame, imu^T_cam从相机坐标系imu平移,imu ^ T_。
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.006422381632411965, 0.019939800449065116, 0.03364235163589248]

#feature traker paprameters特征跟踪参数
max_cnt: 150            # max feature number in feature tracking特征跟踪中，最大特征编号
min_dist: 20            # min distance between two features 两个特征间的最小距离
freq: 20                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 发布跟踪结果的频率(Hz)。至少10赫兹，估算精度高。如果设置为0，则频率与原始图像相同
F_threshold: 1.0        # ransac threshold (pixel)Ransac 阈值(像素)
show_track: 1           # publish tracking image as topic发布跟踪图像作为主题
equalize: 1             # if image is too dark or light, trun on equalize to find enough features如果图像太暗或太亮，均衡旋转找到足够的特征
fisheye: 1              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points如果使用鱼眼，打开它。加载一个圆形掩码去除边缘噪音点

#optimization parameters优化参数
max_solver_time: 0.035   # max solver itration time (ms), to guarantee real time最大解算时间(毫秒) ，以保证实时
max_num_iterations: 10   # max solver itrations, to guarantee real time最大解算能力，保证实时性
keyframe_parallax: 10.0  # keyframe selection threshold (pixel)关键帧选择阈值(像素)

#unsynchronization parameters不同步参数
estimate_td: 0           # online estimate time offset between camera and imu摄像机和 imu 之间的在线估计时间偏移
td: 0                    # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)时间偏移的初始值。单位: 秒读取图像时钟 + td = 实时图像时钟(IMU 时钟)

#rolling shutter parameters滚动快门参数？？
rolling_shutter: 0       # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0    # unit: s. rolling shutter read out time per frame (from data sheet). 

#loop closure parameters回环参数
loop_closure: 1                    # start loop closure开始回环
skip_time: 0.0
skip_dist: 0.0
debug_image: 0                      # save raw image in loop detector for visualization prupose; you can close this function by setting 0 将原始图像保存在循环检测器中以便可视化; 可以通过设置0来关闭此函数
match_image_scale: 0.5
vocabulary_file: "/config/brief_k10L6.bin"
brief_pattern_file: "/config/brief_pattern.yml"